from dataclasses import dataclass

from app.modules.identity.domain.permissions import Permissions


@dataclass(frozen=True, slots=True)
class RoleDefinition:
    name: str
    description: str
    permissions: tuple[str, ...]


DEFAULT_ROLES = (
    RoleDefinition(
        name="owner",
        description="Tenant owner with full administrative access",
        permissions=(
            Permissions.TENANT_READ,
            Permissions.TENANT_MANAGE,
            Permissions.MEMBERSHIP_READ,
            Permissions.MEMBERSHIP_MANAGE,
            Permissions.ROLE_READ,
            Permissions.ROLE_MANAGE,
            Permissions.CUSTOMER_READ,
            Permissions.CUSTOMER_CREATE,
            Permissions.CUSTOMER_UPDATE,
            Permissions.CUSTOMER_DELETE,
            Permissions.LOCATION_READ,
            Permissions.LOCATION_CREATE,
            Permissions.LOCATION_UPDATE,
            Permissions.LOCATION_DELETE,
            Permissions.SHIPMENT_READ,
            Permissions.SHIPMENT_CREATE,
            Permissions.SHIPMENT_UPDATE,
            Permissions.SHIPMENT_DELETE,
            Permissions.SHIPMENT_TRANSITION,
            Permissions.PACKAGE_READ,
            Permissions.PACKAGE_CREATE,
            Permissions.PACKAGE_UPDATE,
            Permissions.PACKAGE_DELETE,
            Permissions.SHIPMENT_EVENT_READ,
            Permissions.SHIPMENT_EVENT_CREATE,
            Permissions.RATE_READ,
            Permissions.RATE_CREATE,
            Permissions.RATE_MANAGE,
            Permissions.PRICING_RULE_READ,
            Permissions.PRICING_RULE_CREATE,
            Permissions.PRICING_RULE_UPDATE,
            Permissions.PRICING_RULE_DELETE,
            Permissions.CARRIER_READ,
            Permissions.CARRIER_CREATE,
            Permissions.CARRIER_UPDATE,
            Permissions.CARRIER_DELETE,
            Permissions.CARRIER_SERVICE_READ,
            Permissions.CARRIER_SERVICE_CREATE,
            Permissions.CARRIER_SERVICE_UPDATE,
            Permissions.CARRIER_SERVICE_DELETE,
            Permissions.DOCUMENT_READ,
            Permissions.DOCUMENT_CREATE,
            Permissions.DOCUMENT_UPDATE,
            Permissions.SHIPMENT_LABEL_READ,
            Permissions.SHIPMENT_LABEL_CREATE,
            Permissions.SHIPMENT_LABEL_UPDATE,
            Permissions.SHIPMENT_LABEL_VOID,
        ),
    ),
    RoleDefinition(
        name="admin",
        description="Tenant administrator",
        permissions=(
            Permissions.TENANT_READ,
            Permissions.MEMBERSHIP_READ,
            Permissions.MEMBERSHIP_MANAGE,
            Permissions.ROLE_READ,
            Permissions.CUSTOMER_READ,
            Permissions.CUSTOMER_CREATE,
            Permissions.CUSTOMER_UPDATE,
            Permissions.CUSTOMER_DELETE,
            Permissions.LOCATION_READ,
            Permissions.LOCATION_CREATE,
            Permissions.LOCATION_UPDATE,
            Permissions.LOCATION_DELETE,
            Permissions.SHIPMENT_READ,
            Permissions.SHIPMENT_CREATE,
            Permissions.SHIPMENT_UPDATE,
            Permissions.SHIPMENT_DELETE,
            Permissions.SHIPMENT_TRANSITION,
            Permissions.PACKAGE_READ,
            Permissions.PACKAGE_CREATE,
            Permissions.PACKAGE_UPDATE,
            Permissions.PACKAGE_DELETE,
            Permissions.SHIPMENT_EVENT_READ,
            Permissions.SHIPMENT_EVENT_CREATE,
            Permissions.RATE_READ,
            Permissions.RATE_CREATE,
            Permissions.RATE_MANAGE,
            Permissions.CARRIER_READ,
            Permissions.CARRIER_CREATE,
            Permissions.CARRIER_UPDATE,
            Permissions.CARRIER_DELETE,
            Permissions.CARRIER_SERVICE_READ,
            Permissions.CARRIER_SERVICE_CREATE,
            Permissions.CARRIER_SERVICE_UPDATE,
            Permissions.CARRIER_SERVICE_DELETE,
            Permissions.DOCUMENT_READ,
            Permissions.DOCUMENT_CREATE,
            Permissions.DOCUMENT_UPDATE,
            Permissions.SHIPMENT_LABEL_READ,
            Permissions.SHIPMENT_LABEL_CREATE,
            Permissions.SHIPMENT_LABEL_UPDATE,
            Permissions.SHIPMENT_LABEL_VOID,
        ),
    ),
    RoleDefinition(
        name="member",
        description="Standard tenant member",
        permissions=(
            Permissions.TENANT_READ,
            Permissions.MEMBERSHIP_READ,
            Permissions.CUSTOMER_READ,
            Permissions.LOCATION_READ,
            Permissions.SHIPMENT_READ,
            Permissions.PACKAGE_READ,
            Permissions.SHIPMENT_EVENT_READ,
            Permissions.RATE_READ,
            Permissions.CARRIER_READ,
            Permissions.CARRIER_SERVICE_READ,
            Permissions.DOCUMENT_READ,
            Permissions.SHIPMENT_LABEL_READ,
        ),
    ),
)
