"""add login lockout fields

Revision ID: 082f86c344fd
Revises: 597f9378db68
Create Date: 2026-08-31 14:14:39.051902
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '082f86c344fd'
down_revision: str | Sequence[str] | None = '597f9378db68'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
