"""create carriers and carrier services

Revision ID: 1b3ad6336232
Revises: 54a0f216dd20
Create Date: 2026-08-28 11:34:59.166045
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = '1b3ad6336232'
down_revision: str | Sequence[str] | None = '54a0f216dd20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_carriers_status_valid')),
    sa.CheckConstraint('char_length(trim(code)) > 0', name=op.f('ck_carriers_code_not_blank')),
    sa.CheckConstraint('char_length(trim(name)) > 0', name=op.f('ck_carriers_name_not_blank')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_carriers_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carriers')),
    sa.UniqueConstraint('tenant_id', 'code', name='carrier_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'id', name='carrier_tenant_id')
    )
    op.create_index('ix_carriers_tenant_status', 'carriers', ['tenant_id', 'status'], unique=False)
    op.create_table('carrier_services',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('service_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_carrier_services_status_valid')),
    sa.CheckConstraint('char_length(trim(code)) > 0', name=op.f('ck_carrier_services_code_not_blank')),
    sa.CheckConstraint('char_length(trim(name)) > 0', name=op.f('ck_carrier_services_name_not_blank')),
    sa.ForeignKeyConstraint(['tenant_id', 'carrier_id'], ['carriers.tenant_id', 'carriers.id'], name='carrier_service_carrier', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carrier_services')),
    sa.UniqueConstraint('tenant_id', 'carrier_id', 'code', name='carrier_service_code')
    )
    op.create_index('ix_carrier_services_tenant_carrier_status', 'carrier_services', ['tenant_id', 'carrier_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_carrier_services_tenant_carrier_status', table_name='carrier_services')
    op.drop_table('carrier_services')
    op.drop_index('ix_carriers_tenant_status', table_name='carriers')
    op.drop_table('carriers')
    # ### end Alembic commands ###
