"""create ledger foundation

Revision ID: 248ab9e8bfac
Revises: 0ba10e0f9618
Create Date: 2026-08-29 12:32:12.999190
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '248ab9e8bfac'
down_revision: str | Sequence[str] | None = '0ba10e0f9618'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(description) <> ''", name=op.f('ck_journal_entries_journal_description_not_blank')),
    sa.CheckConstraint("source_type IN ('invoice_issued', 'payment_posted')", name=op.f('ck_journal_entries_journal_source_type')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_journal_entries_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries')),
    sa.UniqueConstraint('tenant_id', 'id', name='journal_entry_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'source_type', 'source_id', name='journal_entry_tenant_source')
    )
    op.create_index('ix_journal_entries_tenant_posted_at', 'journal_entries', ['tenant_id', 'posted_at'], unique=False)
    op.create_table('ledger_accounts',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(code) <> ''", name=op.f('ck_ledger_accounts_account_code_not_blank')),
    sa.CheckConstraint("btrim(name) <> ''", name=op.f('ck_ledger_accounts_account_name_not_blank')),
    sa.CheckConstraint("purpose IN ('accounts_receivable', 'revenue', 'cash', 'tax_payable')", name=op.f('ck_ledger_accounts_account_purpose')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_ledger_accounts_account_status')),
    sa.CheckConstraint("type IN ('asset', 'liability', 'equity', 'revenue', 'expense')", name=op.f('ck_ledger_accounts_account_type')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_ledger_accounts_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_accounts')),
    sa.UniqueConstraint('tenant_id', 'code', name='ledger_account_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'id', name='ledger_account_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'purpose', name='ledger_account_tenant_purpose')
    )
    op.create_table('journal_lines',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('ledger_account_id', sa.Uuid(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (\n                debit > 0\n                AND credit = 0\n            )\n            OR\n            (\n                credit > 0\n                AND debit = 0\n            )\n            ', name=op.f('ck_journal_lines_journal_line_one_side_only')),
    sa.CheckConstraint('credit >= 0', name=op.f('ck_journal_lines_journal_line_credit_non_negative')),
    sa.CheckConstraint('debit >= 0', name=op.f('ck_journal_lines_journal_line_debit_non_negative')),
    sa.ForeignKeyConstraint(['tenant_id', 'journal_entry_id'], ['journal_entries.tenant_id', 'journal_entries.id'], name=op.f('fk_journal_lines_tenant_id_journal_entry_id_journal_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'ledger_account_id'], ['ledger_accounts.tenant_id', 'ledger_accounts.id'], name=op.f('fk_journal_lines_tenant_id_ledger_account_id_ledger_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_lines')),
    sa.UniqueConstraint('tenant_id', 'id', name='journal_line_tenant_id')
    )
    op.create_index('ix_journal_lines_tenant_account', 'journal_lines', ['tenant_id', 'ledger_account_id'], unique=False)
    op.create_index('ix_journal_lines_tenant_entry', 'journal_lines', ['tenant_id', 'journal_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_journal_lines_tenant_entry', table_name='journal_lines')
    op.drop_index('ix_journal_lines_tenant_account', table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_table('ledger_accounts')
    op.drop_index('ix_journal_entries_tenant_posted_at', table_name='journal_entries')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
