"""create notifications foundation

Revision ID: 4743f7c1308f
Revises: 1eb6932720fc
Create Date: 2026-08-29 18:13:34.777291
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4743f7c1308f'
down_revision: str | Sequence[str] | None = '1eb6932720fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('recipient', sa.String(length=500), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'webhook')", name=op.f('ck_notifications_channel_valid')),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed')", name=op.f('ck_notifications_status_valid')),
    sa.CheckConstraint('length(trim(body)) > 0', name=op.f('ck_notifications_body_nonblank')),
    sa.CheckConstraint('length(trim(event_type)) > 0', name=op.f('ck_notifications_event_type_nonblank')),
    sa.CheckConstraint('length(trim(idempotency_key)) > 0', name=op.f('ck_notifications_idempotency_key_nonblank')),
    sa.CheckConstraint('length(trim(recipient)) > 0', name=op.f('ck_notifications_recipient_nonblank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('tenant_id', 'id', name='notification_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='notification_tenant_idempotency_key')
    )
    op.create_index('ix_notifications_tenant_scheduled_at', 'notifications', ['tenant_id', 'scheduled_at'], unique=False)
    op.create_index('ix_notifications_tenant_status', 'notifications', ['tenant_id', 'status'], unique=False)
    op.create_table('notification_attempts',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failed')", name=op.f('ck_notification_attempts_status_valid')),
    sa.CheckConstraint('attempt_number > 0', name=op.f('ck_notification_attempts_attempt_number_positive')),
    sa.CheckConstraint('length(trim(provider)) > 0', name=op.f('ck_notification_attempts_provider_nonblank')),
    sa.ForeignKeyConstraint(['tenant_id', 'notification_id'], ['notifications.tenant_id', 'notifications.id'], name='notification_attempt_notification_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_attempts')),
    sa.UniqueConstraint('tenant_id', 'id', name='notification_attempt_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'notification_id', 'attempt_number', name='notification_attempt_number')
    )
    op.create_index('ix_notification_attempts_tenant_attempted_at', 'notification_attempts', ['tenant_id', 'attempted_at'], unique=False)
    op.create_index('ix_notification_attempts_tenant_notification', 'notification_attempts', ['tenant_id', 'notification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_attempts_tenant_notification', table_name='notification_attempts')
    op.drop_index('ix_notification_attempts_tenant_attempted_at', table_name='notification_attempts')
    op.drop_table('notification_attempts')
    op.drop_index('ix_notifications_tenant_status', table_name='notifications')
    op.drop_index('ix_notifications_tenant_scheduled_at', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
