"""create billing invoicing foundation

Revision ID: 50a934f25ca1
Revises: beec6fa472a1
Create Date: 2026-08-28 17:42:03.615357
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "50a934f25ca1"
down_revision: str | Sequence[str] | None = "beec6fa472a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Required by the tenant-aware composite foreign key from invoices
    # to customers.
    op.create_unique_constraint(
        "customer_tenant_id",
        "customers",
        ["tenant_id", "id"],
    )

    op.create_table(
        "invoices",
        sa.Column(
            "tenant_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "customer_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "invoice_number",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
        ),
        sa.Column(
            "subtotal",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
        ),
        sa.Column(
            "tax_amount",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
        ),
        sa.Column(
            "total_amount",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
        ),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "due_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "paid_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'issued', 'paid', 'void')",
            name=op.f("ck_invoices_status"),
        ),
        sa.CheckConstraint(
            "subtotal >= 0",
            name=op.f("ck_invoices_subtotal_non_negative"),
        ),
        sa.CheckConstraint(
            "tax_amount >= 0",
            name=op.f("ck_invoices_tax_amount_non_negative"),
        ),
        sa.CheckConstraint(
            "total_amount = subtotal + tax_amount",
            name=op.f("ck_invoices_total_matches_components"),
        ),
        sa.CheckConstraint(
            "total_amount >= 0",
            name=op.f("ck_invoices_total_amount_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customers.tenant_id", "customers.id"],
            name=op.f("fk_invoices_tenant_id_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_invoices_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_invoices"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            name="invoice_tenant_id",
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "invoice_number",
            name="invoice_tenant_invoice_number",
        ),
    )

    op.create_index(
        "ix_invoices_tenant_customer",
        "invoices",
        ["tenant_id", "customer_id"],
        unique=False,
    )

    op.create_index(
        "ix_invoices_tenant_due_at",
        "invoices",
        ["tenant_id", "due_at"],
        unique=False,
    )

    op.create_index(
        "ix_invoices_tenant_status",
        "invoices",
        ["tenant_id", "status"],
        unique=False,
    )

    op.create_table(
        "invoice_lines",
        sa.Column(
            "tenant_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "invoice_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "shipment_id",
            sa.UUID(),
            nullable=True,
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "quantity",
            sa.Numeric(precision=18, scale=4),
            nullable=False,
        ),
        sa.Column(
            "unit_price",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount = round(quantity * unit_price, 2)",
            name=op.f("ck_invoice_lines_amount_matches_components"),
        ),
        sa.CheckConstraint(
            "amount >= 0",
            name=op.f("ck_invoice_lines_amount_non_negative"),
        ),
        sa.CheckConstraint(
            "length(trim(description)) > 0",
            name=op.f("ck_invoice_lines_description_nonblank"),
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name=op.f("ck_invoice_lines_quantity_positive"),
        ),
        sa.CheckConstraint(
            "unit_price >= 0",
            name=op.f("ck_invoice_lines_unit_price_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "invoice_id"],
            ["invoices.tenant_id", "invoices.id"],
            name=op.f("fk_invoice_lines_tenant_id_invoice_id_invoices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "shipment_id"],
            ["shipments.tenant_id", "shipments.id"],
            name=op.f("fk_invoice_lines_tenant_id_shipment_id_shipments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_invoice_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_invoice_lines"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            name="invoice_line_tenant_id",
        ),
    )

    op.create_index(
        "ix_invoice_lines_tenant_invoice",
        "invoice_lines",
        ["tenant_id", "invoice_id"],
        unique=False,
    )

    op.create_index(
        "ix_invoice_lines_tenant_shipment",
        "invoice_lines",
        ["tenant_id", "shipment_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        "ix_invoice_lines_tenant_shipment",
        table_name="invoice_lines",
    )

    op.drop_index(
        "ix_invoice_lines_tenant_invoice",
        table_name="invoice_lines",
    )

    op.drop_table("invoice_lines")

    op.drop_index(
        "ix_invoices_tenant_status",
        table_name="invoices",
    )

    op.drop_index(
        "ix_invoices_tenant_due_at",
        table_name="invoices",
    )

    op.drop_index(
        "ix_invoices_tenant_customer",
        table_name="invoices",
    )

    op.drop_table("invoices")

    # This must be removed only after invoices is dropped because the
    # invoices composite FK depends on it.
    op.drop_constraint(
        "customer_tenant_id",
        "customers",
        type_="unique",
    )

    # ### end Alembic commands ###
