"""add pricing rules

Revision ID: 54a0f216dd20
Revises: 7bf98504fcfd
Create Date: 2026-08-28 10:01:22.224834
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '54a0f216dd20'
down_revision: str | Sequence[str] | None = '7bf98504fcfd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rules',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('service_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('surcharge_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_amount >= 0', name=op.f('ck_pricing_rules_base_amount_non_negative')),
    sa.CheckConstraint('price_per_kg >= 0', name=op.f('ck_pricing_rules_price_per_kg_non_negative')),
    sa.CheckConstraint('surcharge_amount >= 0', name=op.f('ck_pricing_rules_surcharge_amount_non_negative')),
    sa.CheckConstraint('valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from', name=op.f('ck_pricing_rules_validity_range_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_pricing_rules_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_rules'))
    )
    op.create_index('ix_pricing_rules_service_type', 'pricing_rules', ['service_type'], unique=False)
    op.create_index('ix_pricing_rules_status', 'pricing_rules', ['status'], unique=False)
    op.create_index('ix_pricing_rules_tenant_id', 'pricing_rules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pricing_rules_tenant_id', table_name='pricing_rules')
    op.drop_index('ix_pricing_rules_status', table_name='pricing_rules')
    op.drop_index('ix_pricing_rules_service_type', table_name='pricing_rules')
    op.drop_table('pricing_rules')
    # ### end Alembic commands ###
