"""create outbox foundation

Revision ID: 8b479f4b2492
Revises: 4743f7c1308f
Create Date: 2026-08-29 20:46:57.032057
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8b479f4b2492'
down_revision: str | Sequence[str] | None = '4743f7c1308f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_messages',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processed', 'failed')", name=op.f('ck_outbox_messages_status_valid')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_outbox_messages_attempt_count_nonnegative')),
    sa.CheckConstraint('length(trim(event_type)) > 0', name=op.f('ck_outbox_messages_event_type_nonblank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_messages'))
    )
    op.create_index('ix_outbox_messages_status_available_at', 'outbox_messages', ['status', 'available_at'], unique=False)
    op.create_index('ix_outbox_messages_tenant_created_at', 'outbox_messages', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_messages_tenant_created_at', table_name='outbox_messages')
    op.drop_index('ix_outbox_messages_status_available_at', table_name='outbox_messages')
    op.drop_table('outbox_messages')
    # ### end Alembic commands ###
