"""create audit logs

Revision ID: f8fb83e494c1
Revises: 76f397a2dc95
Create Date: 2026-08-30 11:28:37.517964
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f8fb83e494c1'
down_revision: str | Sequence[str] | None = '76f397a2dc95'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_audit_logs_tenant_id_id')
    )
    op.create_index('ix_audit_logs_tenant_action', 'audit_logs', ['tenant_id', 'action'], unique=False)
    op.create_index('ix_audit_logs_tenant_actor', 'audit_logs', ['tenant_id', 'actor_type', 'actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_logs_tenant_occurred', 'audit_logs', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_logs_tenant_resource', 'audit_logs', ['tenant_id', 'resource_type', 'resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_tenant_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_occurred', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_actor', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
